apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: github-source-demo

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - source-flow.yaml

configMapGenerator:
  - name: github-source-demo-content
    files:
      - site/index.html
      - site/styles.css
      - site/app-config.js
