apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: color-showcase

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: color-showcase-content
    files:
      - site/index.html
      - site/styles.css
      - site/app-config.js

