apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-live
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/argoproj/argocd-example-apps.git
      targetRevision: HEAD
      path: guestbook
    - repoURL: git://demo-git.argocd.svc.cluster.local/argocd-demo.git
      targetRevision: main
      path: k8s/guestbook-live-extras
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-live
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
