apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-live
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git://demo-git.argocd.svc.cluster.local/argocd-demo.git
    targetRevision: main
    path: k8s/guestbook-live-enhanced
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-live
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
