apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argocd-example-apps/master/guestbook/guestbook-ui-deployment.yaml
  - https://raw.githubusercontent.com/argoproj/argocd-example-apps/master/guestbook/guestbook-ui-svc.yaml
  - demo-servers.yaml
  - redis.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: guestbook-ui
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /metadata/labels
        value:
          app: guestbook-ui
          app.kubernetes.io/part-of: guestbook-live
      - op: add
        path: /spec/template/metadata/labels/app.kubernetes.io~1part-of
        value: guestbook-live
